home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('gallery', views.gallery, name='gallery'),
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('story1/', include('story1.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('', include('story9.urls'))
]

story5/urls.py
from django.urls import path

from . import views

app_name = 'story5'

urlpatterns = [
    path('hapus', views.hapus, name='hapus'),
    path('matkul', views.matkulku, name= 'matkul'),
    path('jadwal', views.jadwal, name='jadwal')
]
    

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('Kegiatanku', views.kegiatanku, name='kegiatan1')
    # path('Kegiatan2', views.kegiatan2, name='kegiatan2'),
    # path('Kegiatan3', views.kegiatan3, name='kegiatan3')
]

home/models.py
from django.db import models

home/views.py
from django.shortcuts import render
# Create your views here.
def index(request):
    return render(request, 'home/index.html')

def gallery(request):
    return render(request, 'home/gallery.html')

home/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <link href='https://fonts.googleapis.com/css?family=Averia Libre' rel='stylesheet'>
    <title>Story 4</title>

    <div>
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#FFF8F8; font-family: Averia Libre;font-style: normal;font-weight: 300;
      font-size: 20px; line-height: 29px;">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
          <a class="nav-item nav-link" href="{% url 'home:index' %}" >Home</a>
        </div>
          <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link" href="{% url 'story1:story 1' %}">Story 1</a>
            <a class="nav-item nav-link " href="{% url 'home:index' %}#about">About Me <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'home:index' %}#contact">Contact</a>
            <a class="nav-item nav-link" href="{% url 'home:gallery' %}">Gallery</a>
            <a class="nav-item nav-link" href="{% url 'story5:matkul' %}">Matkul</a>
            <a class="nav-item nav-link" href="{% url 'story5:jadwal' %}">jadwalku</a>
            <a class="nav-item nav-link" href="{% url 'story6:kegiatan1' %}">tambah kegiatan</a>
          </div>
        </div>
      </nav>
    </div>
</head>
<body>
  {% block content %}
  
  {% endblock %} 
</body>
</html>