home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('gallery', views.gallery, name='gallery'),
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('story1/', include('story1.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('', include('story9.urls'))
]

story5/urls.py
from django.urls import path

from . import views

app_name = 'story5'

urlpatterns = [
    path('hapus', views.hapus, name='hapus'),
    path('matkul', views.matkulku, name= 'matkul'),
    path('jadwal', views.jadwal, name='jadwal')
]
    

home/models.py
from django.db import models

story5/models.py
from django.db import models
Tahun_CHOICES = [
    ('2018/2019', 'Gasal 2018/2019'),
    ('2018/2019', 'Ganjil 2018/2019'),
    ('2019/2020', 'Gasal 2019/2020'),
    ('2019/2020', 'Ganjil 2019/2020'),
    ('2020/2021', 'Gasal 2020/2021'),
    ('2020/2021', 'Ganjil 2020/2021'),
]

class matkul(models.Model): 
    nama_matkul = models.CharField('Mata Kuliah', max_length = 30) 
    dosen = models.CharField('Nama Dosen', max_length=25) 
    sks = models.PositiveIntegerField()
    deskripsi = models.TextField(max_length=100, null=True)
    tahun = models.CharField('Tahun Ajaran', choices=Tahun_CHOICES, max_length=16)
    ruang = models.CharField(max_length=8)
    last_modified = models.DateTimeField(auto_now_add = True) 
   
        # renames the instances of the model 
        # with their title name 
    def __str__(self): 
        return self.nama_matkul

story5/forms.py
from django import forms 
from .models import matkul 
  
class MatkulForm(forms.ModelForm):  
    class Meta: 
        model = matkul
        fields = ('nama_matkul', 'dosen', 'sks', 'deskripsi', 'tahun', 'ruang')

home/views.py
from django.shortcuts import render
# Create your views here.
def index(request):
    return render(request, 'home/index.html')

def gallery(request):
    return render(request, 'home/gallery.html')

story5/views.py
from django.shortcuts import render, redirect
from .forms import MatkulForm
from .models import matkul

# Create your views here.

def matkulku(request):
    if request.method == 'POST':
        form = MatkulForm(request.POST)
        if form.is_valid():
            form.save()
    form = MatkulForm()
    return render(request, 'home/isiform.html', {'form': form})

def hapus(request):
    hapusform = request.POST.get('input')
    matkul.objects.get(nama_matkul= hapusform).delete()
    return redirect('story5:jadwal')

def jadwal(request):
    form = MatkulForm()
    value = matkul.objects.all()
    return render(request, 'home/jadwal.html', {'form': form, 'value':value})

story5/templates/home/isiform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'home/boostrap.css' %}">
<form method="POST" class="post-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" role="button" type="submit">Save</button>
</form>
{% endblock %}

story5/templates/home/jadwal.html
{% extends "base.html" %}
{% block content %}

<table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Mata Kuliah</th>
        <th scope="col">Nama Dosen</th>
        <th scope="col">Jumlah SKS</th>
        <th scope="col">Deskripsi</th>
        <th scope="col">Tahun Ajaran</th>
        <th scope="col">Ruang Kelas</th>
        <th scope="col"></th>
      </tr>
    </thead>
    {% for forms in value%}
    <tbody>
      <tr>
        <td>{{forms.nama_matkul}}</td>
        <td>{{forms.dosen}}</td>
        <td>{{forms.sks}}</td>
        <td>{{forms.deskripsi}}</td>
        <td>{{forms.tahun}}</td>
        <td>{{forms.ruang}}</td>
        <td><form method="POST" class="post-form" action="{% url 'story5:hapus' %}">
          {% csrf_token %}
          <input type="hidden" name="input" value="{{forms.nama_matkul}}"></input>
          <button class="btn btn-primary">Delete</button>
      </form>
    </tbody>
    {% endfor %}
  </table>
{% endblock %}