home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('gallery', views.gallery, name='gallery'),
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('story1/', include('story1.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('', include('story9.urls'))
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_account, name='login'),
    path('home/', views.home, name='home'),
    path('logout/', views.logout_account, name='logout')
]

story9/models.py
from django.db import models

# Create your models here.

story9/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class registerAccount(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

story9/views.py
from django.shortcuts import render, redirect 
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
from .models import *
from .forms import registerAccount

# Create your views here.
def register(request):
	form = registerAccount()
	if request.method == 'POST':
		form = registerAccount(request.POST)
		if form.is_valid():
			form.save()
			return redirect('story9:login')

	context = {'form':form}
	return render(request, 'register.html', context)

def login_account(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			return redirect('story9:home')
		else:
			messages.info(request, "username or password invalid")

	return render(request, 'login.html')

def home(request):
	return render(request, 'homestory9.html')

def logout_account(request):
	logout(request)
	return redirect('story9:home')

story9/templates/homestory9.html
<html>
<head>
    <link href='https://fonts.googleapis.com/css?family=Averia Libre' rel='stylesheet'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
{% if user.is_authenticated %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">LafqiStory</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> {{user.get_username}}</a></li>
      <li><a href="{%url 'story9:logout'%}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
    </ul>
  </div>
</nav>
{% else %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">LafqiStory</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{%url 'story9:home'%}">Home</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'story9:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up </a></li>
      <li><a href="{%url 'story9:login'%}"><span class="glyphicon glyphicon-log-in"></span> Login </a></li>
    </ul>
  </div>
</nav>
{% endif %}
{% if user.is_authenticated %}
<h3 style="font-size: 50px; margin-top:10rem; text-align: center;"> Selamat datang,  {{user.get_username}}.</h3>
{% else %}
<h3 style="font-size: 30px; margin-top:10rem; text-align: center;"> Anda belum login, silahkan login terlebih dahulu.</h3>
{% endif %}
</body>
</html>

story9/templates/login.html
<html>
<head>
    <link href='https://fonts.googleapis.com/css?family=Averia Libre' rel='stylesheet'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">LafqiStory</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{%url 'story9:home'%}">Home</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{%url 'story9:register'%}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="{%url 'story9:login'%}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
<div class="container" style="width:20%;background-color: #f1f1f1; font-family: Averia Libre; margin-top: 6rem;">
<div class="row justify-content-center">
<div>
<form method="POST" onsubmit="myFunction()" class="post-form; text-center" enctype="multipart/form-data">
                  {% csrf_token %}
                     <div style="font-size: 20px;">Username</div>
                      <input type="text" name="username" id="form-register"></input>
                      <div style="font-size: 20px;">Password</div>
                      <input type="password" name="password" id="form-register"></input>
                
                      <div class="text-center">
                        <br>
                        <button class="btn btn-primary" role="button" type="submit">submit</button>
                      </div>
                    </div>
                    </form>
</form>
</div>
</div>
</div>
</body>
</html>

story9/templates/register.html
<!doctype html>
<html lang="en">
  <head>
    <link href='https://fonts.googleapis.com/css?family=Averia Libre' rel='stylesheet'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">LafqiStory</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{%url 'story9:home'%}">Home</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{%url 'story9:register'%}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="{%url 'story9:login'%}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
</head>
<body>
<div class="container" style="width:20%;background-color: #f1f1f1; font-family: Averia Libre; margin-top: 6rem;">
<div class="row justify-content-center">
<div>
<form method="POST" onsubmit="myFunction()" class="post-form; text-center" style="font-size: 20px;" enctype="multipart/form-data">
                  {%for i in form%}
                  {%csrf_token%}
                     <div style="font-size: 20px">{{i.label_tag}}</div>
                      <div id="form-register">{{i}}</div>
                    {%endfor%}
                      <div class="text-center">
                        <br>
                        <button class="btn btn-primary" role="button" type="submit">sign up</button>
                      </div>
                  
                    </form>
                  </div>
</div>
</div>
</body>
</html>